from bandcamper.__version__ import __author__
from bandcamper.__version__ import __author_email__
from bandcamper.__version__ import __copyright__
from bandcamper.__version__ import __description__
from bandcamper.__version__ import __license__
from bandcamper.__version__ import __title__
from bandcamper.__version__ import __url__
from bandcamper.__version__ import __version__
from bandcamper.bandcamper import Bandcamper
